import nextConfig from "eslint-config-next";

const eslintConfig = [
  {
    ignores: [
      "out/",
      ".next/",
      "dist/",
      "coverage/",
      "node_modules/",
      // Generated by Next.js – contains triple-slash references we intentionally ignore
      "next-env.d.ts",
    ],
  },
  ...nextConfig,
];

export default eslintConfig;
