export const PRICING = {
  OVERAGE_RATE_PER_REQUEST: 0.04,
  BUSINESS_QUOTA: 300,
  ENTERPRISE_QUOTA: 1000,
  ENTERPRISE_UPGRADE_DELTA: 20,
} as const;

// Cost optimization thresholds
export const COST_OPTIMIZATION_THRESHOLDS = {
  MIN_OVERAGE_THRESHOLD: 100,
  APPROACHING_BREAKEVEN_THRESHOLD: 400,
  STRONG_CANDIDATE_THRESHOLD: 500,
} as const;
